name: MLCompEnv
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _py-xgboost-mutex=2.0
  - abseil-cpp=20210324.2
  - absl-py=1.0.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - appnope=0.1.3
  - astor=0.8.1
  - asttokens=2.2.1
  - astunparse=1.6.3
  - async-timeout=4.0.2
  - attrs=21.4.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - cachetools=4.2.4
  - certifi=2023.5.7
  - cffi=1.14.6
  - charset-normalizer=2.0.11
  - click=8.0.3
  - cloudpickle=2.0.0
  - colorama=0.4.4
  - comm=0.1.3
  - cryptography=36.0.1
  - cycler=0.11.0
  - dataclasses=0.8
  - debugpy=1.5.1
  - decorator=4.4.2
  - entrypoints=0.4
  - executing=1.2.0
  - fonttools=4.39.3
  - freetype=2.11.0
  - frozenlist=1.3.0
  - future=0.18.2
  - gast=0.3.3
  - giflib=5.2.1
  - google-auth=1.35.0
  - google-auth-oauthlib=0.4.6
  - google-pasta=0.2.0
  - grpc-cpp=1.37.1
  - grpcio=1.37.1
  - h5py=2.10.0
  - hdf5=1.10.6
  - hyperopt=0.2.5
  - icu=68.2
  - idna=3.3
  - importlib-metadata=4.10.1
  - ipykernel=6.20.2
  - ipython=8.12.0
  - jbig=2.1
  - jedi=0.18.2
  - joblib=1.1.0
  - jpeg=9e
  - jupyter_client=7.3.1
  - jupyter_core=5.3.0
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcurl=7.79.1
  - libcxx=12.0.0
  - libdeflate=1.10
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.3
  - libgfortran=5.0.0
  - libgfortran5=12.2.0
  - liblapack=3.9.0
  - libnghttp2=1.43.0
  - libpng=1.6.37
  - libprotobuf=3.15.8
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtiff=4.3.0
  - libwebp-base=1.3.0
  - libxgboost=1.5.1
  - libzlib=1.2.11
  - llvm-openmp=16.0.1
  - lz4-c=1.9.3
  - markdown=3.3.6
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - matplotlib-inline=0.1.6
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=6.0.2
  - munkres=1.1.4
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - networkx=2.5.1
  - numexpr=2.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - oauthlib=3.2.0
  - olefile=0.46
  - openjpeg=2.4.0
  - openssl=1.1.1t
  - opt_einsum=3.3.0
  - packaging=23.1
  - pandas=1.4.3
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.4
  - platformdirs=2.6.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - protobuf=3.15.8
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-xgboost=1.5.1
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.3.0
  - pymongo=4.0.1
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.9.7
  - python-dateutil=2.8.2
  - python-flatbuffers=1.12
  - python_abi=3.9
  - pytz=2021.3
  - pyu2f=0.1.5
  - pyyaml=6.0
  - pyzmq=22.3.0
  - re2=2021.08.01
  - readline=8.1.2
  - requests=2.27.1
  - requests-oauthlib=1.3.1
  - rsa=4.8
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - seaborn=0.12.2
  - setuptools=58.0.4
  - six=1.16.0
  - snappy=1.1.8
  - sqlite=3.36.0
  - stack_data=0.6.2
  - tbb=2021.5.0
  - tensorboard=2.4.1
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - tensorflow-estimator=2.4.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.3
  - tqdm=4.62.3
  - traitlets=5.9.0
  - typing-extensions=4.0.1
  - typing_extensions=4.0.1
  - tzdata=2021e
  - unicodedata2=15.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.6
  - werkzeug=2.0.2
  - wheel=0.37.0
  - wrapt=1.13.3
  - xgboost=1.5.1
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.7.2
  - zeromq=4.3.4
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.5.2
  - pip:
    - biogeme==3.2.8
    - cython==0.29.30
    - llvmlite==0.39.1
    - numba==0.56.4
    - shap==0.41.0
    - slicer==0.0.7
    - unidecode==1.3.4
